version: '3'

services:
  bdd:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: bucket-list
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

